"use strict";
console.log("HELLOW SIR!");
var dateofBirth = 2003;
var currentYear = 2024;
var myAge = currentYear - dateofBirth;
console.log("My Age is:", myAge);
var lengthofRectangle = 15;
var widthodRectangle = 15;
var areaofRactangle = lengthofRectangle * widthodRectangle;
console.log("AreaofRectangle =", areaofRactangle);
var radiousofCircle = 4.3;
var areaofCircle = 3.14 * radiousofCircle * radiousofCircle;
console.log("The area of circle with radious 4.3 is:", areaofCircle);
var edge = 2;
var areaofCube = 6 * edge * edge;
console.log("The area of cube is:", areaofCube);
var fahrenheit = 64.4;
var celsius = (fahrenheit - 32) * 5 / 9;
console.log("64.4F to celsius", celsius);
var totalSeconds = 120;
var minutes = (totalSeconds / 60);
var seconds = (totalSeconds % 60);
console.log("625 seconds is equal to", minutes, "minutes and", seconds, "seconds");
var a = 2;
var b = ++a * 2;
console.log(b);
var x = 5;
var y = x-- + 2;
console.log(y);
var w = 3;
var z = ++w + w++ + ++w;
console.log(z);
var m = 2;
var n = ++m * m++ * --m;
console.log(n);
var c = 3;
var d = 5;
var letResult = ++c + d-- - c++ + --d;
console.log(letResult);
var o = 2;
var p = 4;
var letQ = o++ + ++p - --o + p--;
console.log(o, p, letQ);
var e = 5;
var f = 3;
var g = 2;
var h = 7;
var letResultAll = ++e * (f-- + g) / --h;
console.log(e, f, g, h, letResultAll);
var q = 2;
var r = 3;
var s = 4;
var result = q++ * (--r + q) / (s-- - r);
console.log(q, s, r, result);
